### PR TITLE
Feature/campaign styles

### PR DESCRIPTION
**Pull request by bitTal**
DO NOT MERGE - pending https://github.com/loggingroads/onboarding/pull/4

This PR includes the branch feature-logging-redux which styles the home page.

It also styles the Campaign backoffice section.

### CODE REVIEW

**Comment by tiagojsag** [comment]
@bitTal this needs a rework. please create a new branch and a new PR, copy the changes you want to keep and discard the rest. Also, try to improve the commit number, this is too much

**Comment by bitTal** [comment]
No problem.

**Comment by simaob** [comment]
Yes very large PRs make it harder to review thoroughly. This is something that we can improve not only during development but also on creating the stories in Pivotal Tracker. We can split tasks into smaller parts for instance. Make things a bit more atomic.

For instance in the case of this feature it could've be built with two or three cumulative PRs, e.g.:
1. Build the scaffold for the page, and create a PR;
2. fork from the branch from point 1, and apply styles for one of the parts of the page, create a PR;
3. fork from the branch from point 2, and do the other styles.

happy to discuss these procedures and happy to breakdown stories if you find them too big! =)

**Comment by tiagojsag** [comment]
@simaob this PR includes the commits of the PR we merged earlier today. I already talked with @bitTal about it, so we will all work together in the future to improve this. Since the other branch needed a few fixes, a rebase here will be complicated. @bitTal let me or @simaob know if you have any  more questions, or if you need our help for anything :)

**Comment by bitTal** [comment]
As this PR also uses the Sortable Capaigns PR, it would be necessary and useful to merge that PR to develop and then create the new one. Otherwise the same mistakes would be repeated.

**Comment by simaob** [comment]
Does this PR still stand or was it replaced by:
- https://github.com/loggingroads/onboarding/pull/12
- https://github.com/loggingroads/onboarding/pull/13

**Comment by bitTal** [comment]
This one was rewritten in other two PR's, @tiagojsag and I decided this could be discarded.

**Comment by simaob** [comment]
Alright =) discarding.

**Pull request closed without merging**
