### PR TITLE
Events page tabs system

### PR DESCRIPTION
**Pull request by dhakelila**
This PR adds the tab component with the events/task tables inside.

### CODE REVIEW

**Comment by simaob** [comment]
Clara, is this referring to this page:

screen shot 2016-08-05 at 17 30 10

It's the behaviour without the styles yet, is that it? Tks!

**Comment by dhakelila** [comment]
Exactly. Sorry for not tell it specifically. 
I'm going to add those styles right now though.

**Comment by simaob** [comment]
OK! =) I'll wait for these. let me know!

**Comment by dhakelila** [comment]
Styles update.

**Comment by simaob** [comment]
the mouse cursor should be the link hand when hovering the tabs.

**Comment by dhakelila** [comment]
indeed

**Comment by simaob** [comment]
Thanks. =)
Another thing I've just noticed is that these tabs should be under the /campaigns/:id page and not the /events page.

See: https://app.zeplin.io/project.html#pid=578cb0201ff145ec099a7977&sid=578cb09b63c10194775f6869

**Comment by dhakelila** [comment]
Ok, so... Now we have the tabs system into the correct section. 

When you go to "campaigns/3" you will see events and task into this endpoint: "api/v1/campaigns/3".

I also reorganize react elements a bit and solved a typo issue. I messed up campaigns with _campaings_.

PD: If you run the project, you will see a console warning, it is only a warning apparently coming from some library. I need to figure out how to silent that warning. (This is not a new issue but I though it was worth to point out)

**Comment by simaob** [comment]
Thanks. Will have a look now =)

**Pull request merged**
